{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2023-26151",
      "description": "Versions of the package asyncua before 0.9.96 are vulnerable to Denial of Service (DoS) such that an attacker can send a malformed packet and as a result, the server will enter into an infinite loop and consume excessive memory.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2023-26151",
      "reportURL": "https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8",
      "timeStamp": "2023-10-04T17:12:00Z"
    },
    {
      "id": "CVE-2023-26151",
      "description": "Versions of the package asyncua before 0.9.96 are vulnerable to Denial of Service (DoS) such that an attacker can send a malformed packet and as a result, the server will enter into an infinite loop and consume excessive memory.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2023-26151",
      "reportURL": "https://github.com/FreeOpcUa/opcua-asyncio/issues/1013",
      "timeStamp": "2023-10-04T17:12:00Z"
    },
    {
      "id": "CVE-2023-26151",
      "description": "Versions of the package asyncua before 0.9.96 are vulnerable to Denial of Service (DoS) such that an attacker can send a malformed packet and as a result, the server will enter into an infinite loop and consume excessive memory.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2023-26151",
      "reportURL": "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709",
      "timeStamp": "2023-10-04T17:12:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2023-26151",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709",
      "added_at": "2023-10-03T11:03:54Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2023-26151",
      "url": "https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8",
      "added_at": "2023-10-04T17:12:00Z",
      "score": 0.4,
      "template_for": ""
    },
    {
      "cve": "CVE-2023-26151",
      "url": "https://github.com/FreeOpcUa/opcua-asyncio/issues/1013",
      "added_at": "2023-10-04T17:12:00Z",
      "score": 0.4,
      "template_for": ""
    },
    {
      "cve": "CVE-2023-26151",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709",
      "added_at": "2023-10-03T11:03:54Z",
      "score": 0.7,
      "template_for": ""
    }
  ]
}
