{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2019-20426",
      "description": "In the Lustre file system before 2.12.3, the ptlrpc module has an out-of-bounds access and panic due to the lack of validation for specific fields of packets sent by a client. In the function ldlm_cancel_hpreq_check, there is no lock_count bounds check.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2019-20426",
      "reportURL": "https://jira.whamcloud.com/browse/LU-12614",
      "timeStamp": "2020-08-24T17:37:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2019-20426",
      "url": "https://lustre.org/",
      "added_at": "1970-01-01T00:00:00Z"
    },
    {
      "id": "CVE-2019-20426",
      "url": "https://wiki.lustre.org/Lustre_2.12.3_Changelog",
      "added_at": "1970-01-01T00:00:00Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2019-20426",
      "url": "https://jira.whamcloud.com/browse/LU-12614",
      "added_at": "2020-08-24T17:37:00Z",
      "score": 0,
      "template_for": ""
    },
    {
      "cve": "CVE-2019-20426",
      "url": "https://lustre.org/",
      "added_at": "1970-01-01T00:00:00Z",
      "score": 0,
      "template_for": ""
    },
    {
      "cve": "CVE-2019-20426",
      "url": "https://wiki.lustre.org/Lustre_2.12.3_Changelog",
      "added_at": "1970-01-01T00:00:00Z",
      "score": 0,
      "template_for": ""
    }
  ]
}
