{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2019-16228",
      "description": "An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2019-16228",
      "reportURL": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/FPE",
      "timeStamp": "2020-09-14T15:21:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2019-16228",
      "url": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/FPE",
      "added_at": "1970-01-01T00:00:00Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2019-16228",
      "url": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/FPE",
      "added_at": "2020-09-14T15:21:00Z",
      "score": 0,
      "template_for": ""
    }
  ]
}
