{
  "exploitdb": [],
  "itw": [],
  "trickest": [
    {
      "id": "CVE-2021-28861",
      "url": "https://bugs.python.org/issue43223",
      "added_at": "1970-01-01T00:00:00Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [
    {
      "cve": "CVE-2021-28861",
      "url": "https://www.cve.news/cve-2021-28861/",
      "addedAt": "2023-01-16T12:39:25Z",
      "score": 1
    }
  ],
  "openpoc": [
    {
      "cve": "CVE-2021-28861",
      "url": "https://bugs.python.org/issue43223",
      "added_at": "1970-01-01T00:00:00Z",
      "score": 0,
      "template_for": ""
    },
    {
      "cve": "CVE-2021-28861",
      "url": "https://www.cve.news/cve-2021-28861/",
      "added_at": "2023-01-16T12:39:25Z",
      "score": 1,
      "template_for": "nuclei"
    }
  ]
}
